#define main accepted_active_preparation_regression_main
#include "../../../../reconstruction/plugins/generators/live-context/test_immediate_preparation.mm"
#undef main
#include "prevoice_channel.hpp"
namespace {
std::vector<uint32_t> repairWords(const veggie_loops::three_osc::prevoice::Snapshot&s){
 std::vector<uint32_t>out;for(int g=0;g<5;++g)for(size_t o=0;o<160;o+=4)if(o!=0x68&&o!=0x6c&&o!=0x78)out.push_back(load<uint32_t>(&s.groups[g],o));return out;
}
}
int main(int argc,char**argv){@autoreleasepool{try{
 require(argc==4,"Usage: handoff <original> <new source DLL> <own data directory/>");
 require(std::fegetround()==FE_TONEAREST,"Nearest-even required");uint64_t fpcr;asm volatile("mrs %0, fpcr":"=r"(fpcr));require((fpcr&((1ull<<24)|(0x1full<<8)))==0,"Nontrapping gradual-underflow domain required");
 require(hashFile(argv[1])=="c4e64bada4f0e8866e8589cb6e7fd0586d83ec53de52491c6111d0bd9395805c","Original wrapper changed");
 require(hashFile("/Applications/FL Studio 2024.app/Contents/Resources/FL/Shared/dsp_ippv2_x64.dylib")=="f0a62121ba6e9fe38eb64a812adb3437a4204cbbc266bc95ff0aaf3df8a76cd1","Original DSP changed");
 require(hashFile("/Applications/FL Studio 2024.app/Contents/Resources/FL/Plugins/Fruity/Generators/3x Osc/engine.dylib")=="d7eda5267ae938c22ca36d11676ffd870d639aec6086954cd7e895b04be8e66f","Original small engine changed");
 const char*enginePath="/Applications/FL Studio 2024.app/Contents/Libs/FLEngine_x64.dylib";require(hashFile(enginePath)=="22d445ddae0bc9f6fe6ab1d53e8b59659b9a9e2a07d441371e3c27704317bd37","Original host changed");
 [NSApplication sharedApplication];dataPath=argv[3];hostMethods.fill(reinterpret_cast<void*>(&noop));pathMethods.fill(reinterpret_cast<void*>(&noop));hostMethods[0xc8/8]=reinterpret_cast<void*>(&hostDispatch);hostMethods[0x1c0/8]=reinterpret_cast<void*>(&nativeLR);hostMethods[0xf0/8]=reinterpret_cast<void*>(&nativeNotify);
 alignas(16)std::array<std::byte,512>host{};store<void*>(host.data(),0,hostMethods.data());std::vector<float>tables(6*16384);veggie_loops::three_osc::legacy::generateTables(std::span<float,6*16384>(tables.data(),tables.size()));for(int i=0;i<6;++i)store<const float*>(host.data(),0x18+i*8,tables.data()+i*16384);
 void*native=dlopen(argv[1],RTLD_NOW|RTLD_LOCAL);require(native,"Original load failed");void*source=dlopen(argv[2],RTLD_NOW|RTLD_LOCAL);require(source,"Source load failed");void*engine=dlopen(enginePath,RTLD_NOW|RTLD_LOCAL);require(engine,"Engine load failed");
 auto create=symbol<void*(*)(void*,intptr_t)>(native,"CreatePlugInstance");auto factory=symbol<vl_private_osc::Plugin*(*)(void*,intptr_t)>(source,"CreatePlugInstance");auto channel=symbol<vl_osc_multimode_channel*(*)(vl_private_osc::Plugin*)>(source,"vl_private_osc_channel");auto cache=symbol<int(*)(vl_private_osc::Plugin*,void*,size_t)>(source,"vl_private_prevoice_cache_snapshot");auto snapshot=symbol<int(*)(const vl_osc_multimode_channel*,const vl_osc_multimode_channel_voice*,uint32_t*,uint8_t*,float*,int32_t*,uint32_t*,uint8_t*)>(source,"vl_osc_multimode_channel_snapshot");
 Dl_info ni{},ei{};require(dladdr(reinterpret_cast<void*>(create),&ni)&&dladdr(dlsym(engine,"CreateFruityInstance"),&ei),"Image bases unavailable");auto*w=static_cast<char*>(ni.dli_fbase);auto*e=static_cast<char*>(ei.dli_fbase);using Ctor=void*(*)(void*,intptr_t,void*);auto hc=reinterpret_cast<Ctor>(e+0xb4cd20),pc=reinterpret_cast<Ctor>(e+0xb4c7c0);
 size_t cacheWords=0,cacheCopies=0,audioFloats=0,renders=0,voiceChecks=0,borrowedChecks=0,recreated=0,callbackPairs=0,fenvRestores=0;std::array<int32_t,6>rates{8000,44100,48000,96000,192000,384000};
 {SavedSpans globals(w,{{0x25892c,24},{0x263008,16}});std::array<void*,5>sm{};sm[3]=reinterpret_cast<void*>(&readStream);sm[4]=reinterpret_cast<void*>(&writeStream);
 for(int f=0;f<96;++f){require(globals.restore(),"Fresh globals not restored");void*p=create(host.data(),42);require(p,"Original factory failed");std::vector<std::pair<intptr_t,int32_t>>notices;std::array<void*,96>mm{};mm[0xc8/8]=reinterpret_cast<void*>(&modelHostDispatch);mm[0x1c0/8]=reinterpret_cast<void*>(&nativeLR);mm[0xf0/8]=reinterpret_cast<void*>(&modelHostNotify);ModelHost mh{mm.data(),&notices};void*ha=hc(e+0x1497870,1,&mh);require(ha,"Host adapter failed");auto*cpp=factory(static_cast<char*>(ha)+16,42);require(cpp,"Source factory failed");void*m=pc(e+0x1497618,1,cpp);require(m,"Plugin adapter failed");
 const auto snap=[&](){veggie_loops::three_osc::prevoice::Snapshot s{};require(cache(cpp,&s,sizeof s),"Cache snapshot failed");return s;};
 const auto compareCache=[&](){const auto s=snap();const auto a=coefficients(load<void*>(p,0x240)),b=repairWords(s);if(a!=b){std::cerr<<"Handoff cache fixture "<<f<<" comparison "<<cacheCopies<<"\n";for(size_t i=0;i<a.size();++i)if(a[i]!=b[i])std::cerr<<i<<" native="<<a[i]<<" source="<<b[i]<<"\n";}require(a==b,"Handoff defined coefficients/history differ");cacheWords+=185;++cacheCopies;return s;};
 auto nd=method<intptr_t(*)(void*,intptr_t,intptr_t,intptr_t)>(p,0xd0),sd=method<intptr_t(*)(void*,intptr_t,intptr_t,intptr_t)>(m,0xd0);auto ne=method<int32_t(*)(void*,int32_t,int32_t,int32_t)>(p,0xf0),se=method<int32_t(*)(void*,int32_t,int32_t,int32_t)>(m,0xf0);auto np=method<int32_t(*)(void*,int32_t,int32_t,uint32_t)>(p,0xf8),sp=method<int32_t(*)(void*,int32_t,int32_t,uint32_t)>(m,0xf8);auto ns=method<void(*)(void*,void*,int32_t)>(p,0xe0),ss=method<void(*)(void*,void*,int32_t)>(m,0xe0);
 nd(p,4,0,rates[f/16]);sd(m,4,0,rates[f/16]);std::array<int32_t,3>sig{16,4,240};nd(p,14,0,reinterpret_cast<intptr_t>(sig.data()));sd(m,14,0,reinterpret_cast<intptr_t>(sig.data()));const float tempo=std::array<float,4>{60,120,180,250}[f%4];ne(p,0,std::bit_cast<int32_t>(tempo),0);se(m,0,std::bit_cast<int32_t>(tempo),0);
 Stream saved{sm.data(),{},0};ns(p,&saved,1);require(saved.bytes.size()==460,"State framing changed");saved.bytes[92]=uint8_t(f%2);ns(p,&saved,0);saved.cursor=0;ss(m,&saved,0);
 const auto set=[&](int id,int value){np(p,id,value,1);sp(m,id,value,1);};std::array<int,21>core{};core[1]=f%5;core[8]=(f+1)%5;core[15]=(f+2)%5;core[6]=80;core[13]=70;for(int i=0;i<21;++i)set(i,core[i]);
 for(int g=0;g<5;++g){const std::array<int32_t,17>raw{f%4,1,100,4000,100,9000,64,12000,g==4?0:g==1?128:8,100,100,g==4?0:4,16000,g%3,16,-32,48};for(int j=0;j<17;++j)set(23+g*17+j,raw[j]);}set(110,128);set(111,32);set(113,f%8);
 compareCache();require(!channel(cpp),"No-voice controls allocated channel");
 const auto pair=[&](auto a,auto b){std::fenv_t before{},after{};require(std::fegetenv(&before)==0,"Handoff caller fenv capture failed");std::feclearexcept(FE_ALL_EXCEPT);a();const int na=std::fetestexcept(FE_ALL_EXCEPT);std::feclearexcept(FE_ALL_EXCEPT);b();const int nb=std::fetestexcept(FE_ALL_EXCEPT);require(std::fesetenv(&before)==0&&std::fegetenv(&after)==0&&!std::memcmp(&before,&after,sizeof before),"Handoff caller fenv restore failed");require(na==nb,"Handoff measured callback FE differs");++callbackPairs;++fenvRestores;compareCache();};
 const auto beforePPQ=snap();sig[2]=960;pair([&]{nd(p,14,0,reinterpret_cast<intptr_t>(sig.data()));},[&]{sd(m,14,0,reinterpret_cast<intptr_t>(sig.data()));});const auto afterPPQ=snap();require(beforePPQ.preparedPPQ==afterPPQ.preparedPPQ&&beforePPQ.preparedTempo==afterPPQ.preparedTempo,"PPQ-only refreshed stored cache contexts");
 const int group=f%5;pair([&]{np(p,23+group*17+3,5000+f,1);},[&]{sp(m,23+group*17+3,5000+f,1);});pair([&]{np(p,23+group*17+14+f%3,0,1);},[&]{sp(m,23+group*17+14+f%3,0,1);});
 auto mixed=snap();for(int g=0;g<5;++g)require(mixed.preparedPPQ[g]==uint32_t(g==group?960:240),"Per-group last prepared context was lost");
 if(f&4){Stream state{sm.data(),{},0};ns(p,&state,1);pair([&]{state.cursor=0;ns(p,&state,0);},[&]{state.cursor=0;ss(m,&state,0);});}
 const auto beforeTrigger=compareCache();require(!channel(cpp),"Pretrigger source channel not lazy");
 std::array<Parameters,2>params{};std::array<vl_osc_multimode_channel_parameters,2>modelParams{};std::array<uintptr_t,2>voices{};std::array<intptr_t,2>handles{};
 const auto trigger=[&](int i){params[i].initial.pitch=float(i?300:-300);params[i].initial.pan=i?.2f:-.2f;params[i].final=params[i].initial;std::memcpy(&modelParams[i],&params[i],40);voices[i]=method<uintptr_t(*)(void*,void*,intptr_t)>(p,0x110)(p,&params[i],100+f*2+i);handles[i]=method<intptr_t(*)(void*,void*,intptr_t)>(m,0x110)(m,&modelParams[i],100+f*2+i);require(voices[i]&&handles[i]&&handles[i]!=-1,"Handoff trigger failed");require(!std::memcmp(&params[i],&modelParams[i],40),"Handoff borrowed params differ");++borrowedChecks;compareCache();};
 trigger(0);const auto imported=snap();require(beforeTrigger.preparedTempo==imported.preparedTempo&&beforeTrigger.preparedPPQ==imported.preparedPPQ,"First-trigger cache recomputed from current context");trigger(1);
 const auto compareVoices=[&](){for(int i=0;i<2;++i)if(voices[i]){VoiceSnapshot a{},b{};const void*editor=load<void*>(reinterpret_cast<void*>(voices[i]),48);std::memcpy(a.mod.data(),static_cast<const char*>(editor)+0x50,180);std::memcpy(a.filter.data(),static_cast<const char*>(editor)+0x108,112);std::memcpy(a.gain.data(),static_cast<const char*>(editor)+0x40,8);a.released={load<int32_t>(editor,0xc),load<int32_t>(editor,0x10),load<uint8_t>(editor,0x178)};std::memcpy(a.phase.data(),reinterpret_cast<const char*>(voices[i])+16,24);a.stereo=load<uint8_t>(reinterpret_cast<void*>(voices[i]),40);std::memcpy(a.parameters.data(),&params[i],40);require(snapshot(channel(cpp),reinterpret_cast<vl_osc_multimode_channel_voice*>(handles[i]),b.mod.data(),b.filter.data(),b.gain.data(),b.released.data(),b.phase.data(),&b.stereo),"Handoff voice snapshot failed");std::memcpy(b.parameters.data(),&modelParams[i],40);require(equal(a,b),"Handoff voice state differs");++voiceChecks;}};
 compareVoices();for(int count:{1,7,8,63,441,1024,16,3}){method<void(*)(void*)>(p,0x138)(p);method<void(*)(void*)>(m,0x138)(m);std::vector<float>a(size_t(count)*2+16,1234.5f);for(int j=0;j<count*2;++j)a[size_t(j)+8]=.25f;auto b=a;nativeNotices.clear();notices.clear();int n=count,ml=count;method<void(*)(void*,float*,int*)>(p,0x108)(p,a.data()+8,&n);method<void(*)(void*,float*,int32_t&)>(m,0x108)(m,b.data()+8,ml);require(n==count&&ml==count,"Handoff render changed count");for(int j=0;j<8;++j)require(a[size_t(j)]==1234.5f&&b[size_t(j)]==1234.5f&&a[size_t(count)*2+8+j]==1234.5f&&b[size_t(count)*2+8+j]==1234.5f,"Handoff render guard changed");require(!std::memcmp(a.data()+8,b.data()+8,size_t(count)*8),"Handoff rendered sample differs");require(nativeNotices==notices,"Handoff notices differ");audioFloats+=size_t(count)*2;++renders;compareVoices();}
 for(int i=0;i<2;++i){method<void(*)(void*,uintptr_t)>(p,0x120)(p,voices[i]);method<void(*)(void*,intptr_t)>(m,0x120)(m,handles[i]);voices[i]=0;}
 if(f%6==0){const auto prior=compareCache();sig[2]=480;pair([&]{nd(p,14,0,reinterpret_cast<intptr_t>(sig.data()));},[&]{sd(m,14,0,reinterpret_cast<intptr_t>(sig.data()));});require(!channel(cpp),"Empty channel was not discarded for no-voice delivery");require(snap().preparedPPQ==prior.preparedPPQ,"Last-voice boundary lost prepared PPQ");trigger(0);require(snap().preparedPPQ==prior.preparedPPQ,"Recreated channel lost prepared PPQ");compareVoices();method<void(*)(void*,uintptr_t)>(p,0x120)(p,voices[0]);method<void(*)(void*,intptr_t)>(m,0x120)(m,handles[0]);++recreated;}
 method<void(*)(void*)>(p,0xc8)(p);method<void(*)(void*)>(m,0xc8)(m);method<void(*)(void*,intptr_t)>(m,0x60)(m,1);method<void(*)(void*,intptr_t)>(ha,0x60)(ha,1);
 }require(globals.restore(),"Handoff native globals not restored/read back");}
 dlclose(source);dlclose(native);dlclose(engine);std::cout<<"{\"status\":\"passed_prevoice_cache_handoff\",\"fixtures\":96,\"sample_rate_profiles\":6,\"measured_callback_pairs\":"<<callbackPairs<<",\"full_fenv_restorations\":"<<fenvRestores<<",\"cache_comparisons\":"<<cacheCopies<<",\"exact_cached_words\":"<<cacheWords<<",\"voice_comparisons\":"<<voiceChecks<<",\"exact_voice_state_values\":"<<voiceChecks*95<<",\"borrowed_parameter_checks\":"<<borrowedChecks<<",\"render_calls\":"<<renders<<",\"exact_audio_floats\":"<<audioFloats<<",\"last_voice_channel_recreations\":"<<recreated<<",\"selected_globals_restored\":true,\"fresh_without_rate_audio_equivalence\":false,\"full_plugin_equivalence\":false}\n";return 0;
 }catch(const std::exception&x){std::cerr<<x.what()<<'\n';return 1;}}}
